### ISSUE TITLE
help: Keep the js files from useHead composable

### ISSUE THREAD

**Issue by kasadawa** [danielroe/nuxt-zero-js#254]
### 📚 What are you trying to do?

I would love to use the package, but its removing not only the scripts, which are related to the hydration, but also the ones, which are added using useHead({}) composable. 
Is there a way to configure the package in a way, not to remove the JS, which is intentionally added in the head ?

Currently using Nuxt 3.11 .

**Comment by danielroe** [comment]
This should now be built-in to Nuxt, with the following config:

```ts
export default defineNuxtConfig({
  features: {
    noScripts: true
  }
})
```

I need to update this repo to make this clearer that it is no longer needed.

**Comment by kasadawa** [comment]
Thanks for mentioning. I tried this config several times before, but it doesn't seem to work on dev server, only for prod ready build.
